import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const siteRoot = path.resolve(__dirname, '..', '..');

export const DEFAULT_CONTENT_REPO_PATH = path.resolve(siteRoot, '..', 'engineering-notebook-content');
export const GENERATED_CONTENT_PATH = path.resolve(siteRoot, 'src', 'generated', 'notebook-content.ts');

marked.setOptions({
  gfm: true,
  breaks: true,
});

export function resolveContentRepoPath(explicitPath) {
  const chosen = explicitPath || process.env.CONTENT_REPO_PATH || DEFAULT_CONTENT_REPO_PATH;
  return path.resolve(chosen);
}

function normalizeDate(input) {
  if (!input) return '1970-01-01';
  const date = new Date(input);
  if (Number.isNaN(date.getTime())) {
    return String(input);
  }
  return date.toISOString().slice(0, 10);
}

function sortByDateDescending(items) {
  return [...items].sort((left, right) => normalizeDate(right.date).localeCompare(normalizeDate(left.date)));
}

function ensureArray(value) {
  return Array.isArray(value) ? value : [];
}

function createId(frontmatter, filePath) {
  return frontmatter.slug || path.basename(filePath, path.extname(filePath));
}

async function readMarkdownFiles(directory) {
  try {
    const entries = await fs.readdir(directory, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
      .map((entry) => path.join(directory, entry.name));
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return [];
    }
    throw error;
  }
}

function parseEssay(filePath, source) {
  const { data, content } = matter(source);
  return {
    id: createId(data, filePath),
    title: data.title,
    date: data.date,
    readTime: data.readTime ?? '',
    category: data.category ?? 'Essay',
    summary: data.summary ?? '',
    content,
    contentHtml: marked.parse(content),
    tags: ensureArray(data.tags),
  };
}

function parseBuildLog(filePath, source) {
  const { data, content } = matter(source);
  return {
    id: createId(data, filePath),
    title: data.title,
    subtitle: data.subtitle ?? '',
    category: data.category ?? 'Build Log',
    difficulty: data.difficulty ?? 'Intermediate',
    tags: ensureArray(data.tags),
    problem: data.problem ?? '',
    originalDesign: data.originalDesign ?? '',
    gaps: data.gaps ?? '',
    improvements: data.improvements ?? '',
    lessons: data.lessons ?? '',
    decision: data.decision ?? '',
    alternativeConsidered: data.alternativeConsidered ?? '',
    whyRejected: data.whyRejected ?? '',
    evidenceLink: data.evidenceLink ?? '',
    interactiveComponentId: data.interactiveComponentId ?? '',
    systemDiagramSpec: data.systemDiagramSpec ?? '',
    body: content,
    bodyHtml: marked.parse(content),
    date: data.date ?? '',
  };
}

function parseLearningNote(filePath, source) {
  const { data, content } = matter(source);
  return {
    id: createId(data, filePath),
    title: data.title,
    author: data.author ?? '',
    source: data.source ?? '',
    sourceType: data.sourceType ?? 'Book',
    date: data.date ?? '',
    keyInsights: ensureArray(data.keyInsights),
    evidence: data.evidence ?? '',
    reflection: data.reflection ?? '',
    actionableTakeaways: ensureArray(data.actionableTakeaways),
    notes: content,
    notesHtml: marked.parse(content),
  };
}

export async function loadNotebookContent(contentRepoPath) {
  const repoRoot = resolveContentRepoPath(contentRepoPath);

  const essaysDir = path.join(repoRoot, 'essays');
  const buildLogsDir = path.join(repoRoot, 'build-logs');
  const learningNotesDir = path.join(repoRoot, 'learning-notes');

  const [essayFiles, buildLogFiles, learningNoteFiles] = await Promise.all([
    readMarkdownFiles(essaysDir),
    readMarkdownFiles(buildLogsDir),
    readMarkdownFiles(learningNotesDir),
  ]);

  const notes = await Promise.all(
    essayFiles.map(async (filePath) => parseEssay(filePath, await fs.readFile(filePath, 'utf8'))),
  );
  const projects = await Promise.all(
    buildLogFiles.map(async (filePath) => parseBuildLog(filePath, await fs.readFile(filePath, 'utf8'))),
  );
  const readingNotes = await Promise.all(
    learningNoteFiles.map(async (filePath) => parseLearningNote(filePath, await fs.readFile(filePath, 'utf8'))),
  );

  return {
    notes: sortByDateDescending(notes),
    projects: sortByDateDescending(projects),
    readingNotes: sortByDateDescending(readingNotes),
  };
}

export function generateContentModule({ notes, projects, readingNotes }, repoPath) {
  return `/**
 * This file is autogenerated by scripts/content/build-content.mjs
 * Source repo: ${repoPath.replace(/\\/g, '/')}
 */

export const NOTES_DATA = ${JSON.stringify(notes, null, 2)} as const;

export const PROJECTS_DATA = ${JSON.stringify(projects, null, 2)} as const;

export const READING_NOTES_DATA = ${JSON.stringify(readingNotes, null, 2)} as const;
`;
}

export async function writeGeneratedContent(contentRepoPath) {
  const repoRoot = resolveContentRepoPath(contentRepoPath);
  const notebook = await loadNotebookContent(repoRoot);
  const moduleSource = generateContentModule(notebook, repoRoot);

  await fs.mkdir(path.dirname(GENERATED_CONTENT_PATH), { recursive: true });
  await fs.writeFile(GENERATED_CONTENT_PATH, moduleSource, 'utf8');

  return {
    repoRoot,
    outputPath: GENERATED_CONTENT_PATH,
    ...notebook,
  };
}

if (process.argv[1] === __filename) {
  const result = await writeGeneratedContent(process.argv[2]);
  console.log(
    `Generated ${path.relative(siteRoot, result.outputPath)} from ${result.repoRoot} (${result.notes.length} essays, ${result.projects.length} build logs, ${result.readingNotes.length} learning notes)`,
  );
}
